"""Remove operation type from Category

Revision ID: efb085db0507
Revises: 7bc4562d9a0d
Create Date: 2026-04-22 14:28:22.648513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efb085db0507'
down_revision: Union[str, Sequence[str], None] = '7bc4562d9a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('type', postgresql.ENUM('income', 'expense', name='operationtype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
